[package]
name = "partition_fxn_example"
version = "0.1.0"
authors = ["nicholasnjihia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
